CREATE DATABASE salesdb;

GO
USE salesdb

GO
CREATE TABLE Customers
(
	Id INT IDENTITY PRIMARY KEY NOT NULL,
	LastName NVARCHAR(20) NOT NULL,
	FirstName NVARCHAR(20) NOT NULL,
	Patronymic NVARCHAR(20) NOT NULL,
	City NVARCHAR(20) NOT NULL
);

GO
CREATE TABLE Sellers
(
	Id INT IDENTITY PRIMARY KEY NOT NULL,
	LastName NVARCHAR(20) NOT NULL,
	FirstName NVARCHAR(20) NOT NULL,
	Patronymic NVARCHAR(20) NOT NULL,
	City NVARCHAR(20) NOT NULL,
	CommissionPercent NUMERIC(18, 9) NOT NULL
);

GO
CREATE TABLE Orders
(
	Id INT IDENTITY PRIMARY KEY NOT NULL,
	Specification NVARCHAR(1000) NOT NULL,

	Amount NUMERIC(18, 9) NOT NULL 
		CONSTRAINT CK_Order_Amount CHECK(Amount > 0),

	OrderDateTime DATETIME NOT NULL,
	City NVARCHAR(20) NOT NULL,
	CommissionPercent NUMERIC(18, 9) NOT NULL,

	CustomerId INT NOT NULL REFERENCES Customers(Id) ON DELETE CASCADE,
	SellerId INT  NOT NULL REFERENCES Sellers(Id) ON DELETE CASCADE,
);

GO
CREATE TABLE HistoryOfOrders
(
	Id INT IDENTITY PRIMARY KEY NOT NULL,
	Operation NVARCHAR(200) NOT NULL,
	OperationDateTime DATETIME NOT NULL DEFAULT GETDATE(),
	OrderDateTime DATETIME NOT NULL,
	CustomerId INT NOT NULL REFERENCES Customers(Id) ON DELETE CASCADE,
	SellerId INT  NOT NULL REFERENCES Sellers(Id) ON DELETE CASCADE,
);
